Repository dargven/Cyborgs, pull requests merged in 2023-11, with the labels that each got.

#42 Fix Structure, Fix answer from server
  API.md
  client/src/App.tsx
  client/src/components/navBar.tsx
  client/src/components/privateRoute.tsx
  client/src/config.ts
  client/src/modules/Server/Server.ts
  client/src/modules/Server/types.ts
  client/src/modules/Store/Store.ts
  client/src/routes/LoginPage.tsx
  server/application/Answer.php
  server/application/Application.php
  server/application/modules/DB/DB.php
  server/application/modules/Lobby/Lobby.php
  server/application/modules/User/User.php
  server/cyborgs.sql
  server/index.php
Labels: bug

#43 HOTFIX обработка ошибок
  server/application/Answer.php
  server/application/Application.php
  server/application/modules/Lobby/Lobby.php
  server/application/modules/User/User.php
  server/cyborgs.sql
Labels: bug

#64 Task-12-Fix
  .idea/Cyborgs-1.iml
  .idea/dataSources.local.xml
  .idea/dataSources.xml
  .idea/dataSources/68681bfd-cc6a-424e-a2e5-c80de797d3cb.xml
  .idea/dataSources/68681bfd-cc6a-424e-a2e5-c80de797d3cb/storage_v2/_src_/schema/dargvetg_cyborgs.UCEyLQ.meta
  .idea/dataSources/68681bfd-cc6a-424e-a2e5-c80de797d3cb/storage_v2/_src_/schema/information_schema.FNRwLQ.meta
  .idea/modules.xml
  .idea/workspace.xml
  API.md
  server/application/Application.php
  server/application/modules/DB/DB.php
  server/application/modules/Game/Game.php
  server/application/modules/Lobby/Lobby.php
  server/index.php
Labels: bug, documentation

#66 Fix-Back, Task-12, Task-B-14
  client/src/config.ts
  server/application/Application.php
  server/application/modules/DB/DB.php
Labels: Improvements

#77 HOTFix2
  .idea/dataSources.local.xml
  .idea/workspace.xml
  client/src/config.ts
Labels: Improvements

#85 FixOnline
  server/application/Application.php
Labels: Improvements

#91 FixAfterFrontEnd(sendEmails)
  server/application/Application.php
  server/application/modules/User/User.php
  server/index.php
  server/vendor/composer/installed.php
Labels: bug, Improvements

#98 FixReadme
  readme.md
Labels: Improvements

#99 Rewrite Readme
  readme.md
Labels: Improvements

#102 RecoveryCss
  client/src/Auth.css
  client/src/routes/PaswordRecovery.tsx
Labels: Improvements

#103 Add methods to API.md
  API.md
Labels: Improvements

#108 useKeyHandler
  client/src/components/Chat/Chat.css
  client/src/hooks/useKeyHandler.ts
  client/src/routes/GamePage.tsx
  client/src/routes/LoginPage.tsx
  client/src/routes/PaswordRecovery.tsx
  client/src/routes/RegistrationPage.tsx
Labels: Improvements

#110 FixChat
  client/src/components/Chat/Chat.tsx
  client/src/config.ts
  server/application/modules/DB/DB.php
Labels: Improvements

#112 Gd 64
  client/src/modules/Server/Server.ts
  client/src/modules/Server/types.ts
Labels: enhancement, Improvements

#111 ico
  client/public/assets/image/Robot_favikon.png
  client/public/index.html
Labels: Improvements

#113 keyHandler
  client/src/components/Chat/Chat.tsx
  client/src/routes/GamePage.tsx
  client/src/routes/PaswordRecovery.tsx
Labels: Improvements

#115 Api.md
  API.md
Labels: Improvements

#119 Correct time
  client/src/components/Chat/Chat.tsx
  client/src/routes/GamePage.tsx
Labels: Improvements

#120 disable login
  client/src/components/privateRoute.tsx
  client/src/routes/LoginPage.tsx
  client/src/routes/PaswordRecovery.tsx
  client/src/routes/RegistrationPage.tsx
Labels: Improvements

#122 F 42
  client/src/Auth.css
  client/src/components/Chat/Chat.css
  client/src/components/Chat/Chat.tsx
  client/src/routes/PaswordRecovery.tsx
Labels: Improvements

#125 add enter event
  client/src/App.tsx
  client/src/components/navButton.tsx
  client/src/routes/MainPage.tsx
Labels: Improvements

#124 Starpage
  client/src/App.tsx
  client/src/Main.css
  client/src/StartPage.css
  client/src/routes/StartPage.tsx
Labels: Improvements

#128 Esc Button
  client/src/popUpMenu.css
  client/src/routes/GamePage.tsx
Labels: Improvements

#133 AddOnlineMethods
  API.md
  client/src/App.tsx
  client/src/config.ts
  server/application/Answer.php
  server/application/Application.php
  server/application/modules/Chat/Chat.php
  server/application/modules/DB/Config/Config.php
  server/application/modules/DB/DB.php
  server/application/modules/Game/Game.php
  server/application/modules/Lobby/Lobby.php
  server/application/modules/Mailer/Mailer.php
  server/application/modules/User/User.php
  server/index.php
  server/src/@mail/password/PaswordRecovery.html
  server/src/Mail/PasswordRecovery/PaswordRecovery.html
Labels: Improvements

#132 F 43
  client/src/components/Chat/Chat.tsx
  client/src/routes/LoginPage.tsx
  client/src/routes/PaswordRecovery.tsx
  client/src/routes/RegistrationPage.tsx
Labels: Improvements

#131 F 52
  client/src/App.tsx
  client/src/components/Chat/Chat.tsx
  client/src/routes/GamePage.tsx
Labels: Improvements

#135 useInterval test
  client/package-lock.json
  client/package.json
  client/src/components/Game/Game.tsx
  client/src/components/Game/Player.tsx
  client/src/components/Game/Scene.tsx
  client/src/config.ts
  client/src/modules/Server/Server.ts
  client/src/routes/GamePage.tsx
Labels: Improvements

#137 F 20
  client/src/App.tsx
  client/src/components/Chat/Chat.tsx
  client/src/components/navBar.tsx
  client/src/components/privateRoute.tsx
  client/src/getSkins.ts
  client/src/modules/Server/Server.ts
  client/src/modules/Store/Store.ts
  client/src/routes/GamePage.tsx
  client/src/routes/MainPage.tsx
  client/src/routes/PaswordRecovery.tsx
  client/src/routes/StartPage.tsx
Labels: Improvements

#140 AddOnline
  server/application/Application.php
  server/application/modules/DB/DB.php
  server/application/modules/Game/Game.php
Labels: enhancement, Improvements
